kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: scaleio-storage
provisioner: kubernetes.io/scaleio
parameters:
  gateway: https://192.168.0.201:443/api
  system: scaleio
  protectionDomain: pd1
  storagePool: pd1_01
  secretRef: sio-secret
  fsType: xfs

